server:
  port: 8383

spring:
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:4433/customer_db
    username: app_user
    password: password
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S
